### ISSUE TITLE
0 out of () SNPs passed

### ISSUE THREAD

**Issue by wingkyBs** [huangyh09/vireo-manual#1]
Hello.
When I run load_cellSNP_vcf, I get the message "0 out of 774295 SNPs passed."
___
Scanning file to determine attributes.
File attributes:
  meta lines: 34
  header_line: 35
  variant count: 774295
  column count: 25
Meta line 34 read in.
All meta lines processed.
gt matrix initialized.
Character matrix gt created.
  Character matrix gt rows: 774295
  Character matrix gt cols: 25
  skip: 0
  nrows: 774295
  row_num: 0
Processed variant: 774295
All variants processed
[1] "0 out of 774295 SNPs passed."
___

I used the vcf file obtained through genotyping as input.
___
##fileformat=VCFv4.2														
##source=gtc_to_vcf 1.2.1														
##reference=file:///mnt/garnet/Tools/GTCtoVCF-1.2.1/ref_fasta/GRCh37.fa														
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">														
##contig=<ID=chr1,length=249250621>														
##contig=<ID=chr2,length=243199373>														
##contig=<ID=chr3,length=198022430>														
##contig=<ID=chr4,length=191154276>														
##contig=<ID=chr5,length=180915260>														
##contig=<ID=chr6,length=171115067>														
##contig=<ID=chr7,length=159138663>														
##contig=<ID=chr8,length=146364022>														
##contig=<ID=chr9,length=141213431>														
##contig=<ID=chr10,length=135534747>														
##contig=<ID=chr11,length=135006516>														
##contig=<ID=chr12,length=133851895>														
##contig=<ID=chr13,length=115169878>														
##contig=<ID=chr14,length=107349540>														
##contig=<ID=chr15,length=102531392>														
##contig=<ID=chr16,length=90354753>														
##contig=<ID=chr17,length=81195210>														
##contig=<ID=chr18,length=78077248>														
##contig=<ID=chr19,length=59128983>														
##contig=<ID=chr20,length=63025520>														
##contig=<ID=chr21,length=48129895>														
##contig=<ID=chr22,length=51304566>														
##contig=<ID=chrX,length=155270560>														
##contig=<ID=chrY,length=59373566>														
##contig=<ID=chrM,length=16569>														
##source_20221101.1=vcf-merge(v0.1.14-12-gcdb80b8) 206898600086_R01C01.vcf.gz 206898600086_R02C01.vcf.gz 206898600086_R03C01.vcf.gz 206898600086_R04C01.vcf.gz 206898610074_R01C02.vcf.gz 206898610074_R02C02.vcf.gz 206898610074_R03C02.vcf.gz 206898610074_R04C02.vcf.gz 206898610074_R05C02.vcf.gz 206898610074_R06C02.vcf.gz 206898610074_R07C02.vcf.gz 206898610074_R08C02.vcf.gz 206898610074_R09C02.vcf.gz 206898610074_R10C02.vcf.gz 206898610074_R11C02.vcf.gz 206898610074_R12C02.vcf.gz														
##sourceFiles_20221101.1=0:206898600086_R01C01.vcf.gz,1:206898600086_R02C01.vcf.gz,2:206898600086_R03C01.vcf.gz,3:206898600086_R04C01.vcf.gz,4:206898610074_R01C02.vcf.gz,5:206898610074_R02C02.vcf.gz,6:206898610074_R03C02.vcf.gz,7:206898610074_R04C02.vcf.gz,8:206898610074_R05C02.vcf.gz,9:206898610074_R06C02.vcf.gz,10:206898610074_R07C02.vcf.gz,11:206898610074_R08C02.vcf.gz,12:206898610074_R09C02.vcf.gz,13:206898610074_R10C02.vcf.gz,14:206898610074_R11C02.vcf.gz,15:206898610074_R12C02.vcf.gz														
##INFO=<ID=SF,Number=.,Type=String,Description="Source File (index to sourceFiles, f when filtered)">														
##INFO=<ID=AC,Number=.,Type=Integer,Description="Allele count in genotypes">														
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">														
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	26_VF_1	56_VF_P	61_VF_R	41_VF	31_VF_R	21_VF_R
chr1	58814	GSA-rs114420996	G	A	.	PASS	AC=6;AN=30;SF=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15	GT	0/0	0/0	0/0	0/0	0/0	0/0
chr1	72526	GSA-1:72526	A	G	.	PASS	AC=0;AN=28;SF=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15	GT	0/0	0/0	0/0	0/0	0/0	0/0
chr1	74792	GSA-rs13328684	G	A	.	PASS	AC=24;AN=24;SF=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15	GT	1/1	./.	1/1	1/1	1/1	1/1
___
Can you please check what the problem is?

Thanks.
Bae.

**Comment by huangyh09** [comment]
Not sure how you got here, but the vireo-manual is for the Cardelino R package, which has been deprecated.

Please use the Vireo Python package:
* https://vireosnp.readthedocs.io
* https://github.com/single-cell-genetics/vireo

Yuanhua

**Comment by huangyh09** [comment]
I will close this issue, the website and archive this repository now.
